--- 
services: 
  eureka-server: 
    image: "bhawani91/servicerg:4"
    ports: 
      - "8761:8761"    
  user: 
    image: "bhawani91/user:4"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    links: 
      - eureka-server
      - zipkin
      - rabbitmq  
    ports: 
      - "8082:8082"
  depart:
    image: "bhawani91/depart:4"      
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    links:
      - eureka-server
      - zipkin
      - rabbitmq  
    ports:
      - "8081:8081"
  gateway:
    image: "bhawani91/gateway:latest"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    links:
      - user
      - depart
      - eureka-server
      - zipkin
      - rabbitmq  
    ports:
      - "9191:9191" 
  zipkin:
    image: openzipkin/zipkin
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    ports:
      - "9411:9411"
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    ports:
      - "15672:15672"      
version: "3" 
